name-template: 'v$RESOLVED_VERSION 🚀'
tag-template: '$RESOLVED_VERSION'

categories:
  - title: '🔥 Breaking Changes'
    semver-increment: 'major'
    when:
      labels:
        - 'breaking-change'
  - title: '🎉 New'
    semver-increment: 'minor'
    when:
      labels:
        - 'feature'
        - 'enhancement'
  - title: '🐛 Fixes'
    semver-increment: 'patch'
    when:
      labels:
        - 'bug'
  - title: '📦 Dependency Updates'
    semver-increment: 'patch'
    when:
      labels:
        - 'dependencies'
  - title: '🔧 Maintenance'
    semver-increment: 'patch'
    when:
      labels:
        - 'chore'
        - 'internal'
        - 'maintenance'
  - title: 'Other Changes'

autolabeler:
  - label: 'breaking-change'
    branch:
      - '/breaking\/.+/'
    title:
      - '(?i)^breaking.*'
  - label: 'feature'
    branch:
      - '/feat\/.+/'
    title:
      - '(?i)^feat.*'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '(?i)^fix.*'
  - label: 'dependencies'
    branch:
      - '/dependabot\/.+/'
      - '/renovate\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'

template: "$CHANGES"
