apiVersion: v2
name: sample-app
description: A Helm chart for deploying the sample FastAPI app
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: application
    version: "6.5.0"
    repository: "https://stakater.github.io/stakater-charts"
  - name: postgresql
    condition: postgresql.enabled
    version: "16.7.21"
    repository: "https://charts.bitnami.com/bitnami"
