application:
  deployment:
    image:
      repository: ghcr.io/roberdvs/sample-app
      tag: main
    env:
      DATABASE_URL:
        value: postgresql://postgres:postgres@sample-app-postgresql:5432/example
    initContainers:
      - name: wait-for-database
        image: postgres:17-alpine
        command: ['sh', '-c', 'until pg_isready -h sample-app-postgresql -p 5432 -U postgres; do echo waiting for database; sleep 2; done;']
    ports:
      - containerPort: 8000
        name: http
        protocol: TCP

    startupProbe:
      enabled: true
      httpGet:
        path: /health/ready
        port: 8000
      initialDelaySeconds: 15
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
      periodSeconds: 10
    readinessProbe:
      enabled: true
      httpGet:
        path: /health/ready
        port: 8000
      initialDelaySeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
      successThreshold: 1
      periodSeconds: 5
    livenessProbe:
      enabled: true
      httpGet:
        path: /health/live
        port: 8000
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
      periodSeconds: 10

  service:
    type: NodePort
    ports:
    - port: 8000
      name: http
      protocol: TCP
      targetPort: 8000

  ingress:
    enabled: true
    hosts:
      - host: sample-app.local
        paths:
          - path: /
            pathType: Prefix

postgresql:
  # Disable PostgreSQL in-cluster deployment if using an external database like AWS RDS
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: example
