name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  contents: read
  pull-requests: write

jobs:
  ci-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Set up Python"
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run unit tests
        run: |
          uv run coverage run -m pytest app/tests/unit/
          uv run coverage report
          uv run coverage xml

      - name: Report Coverage
        uses: orgoro/coverage@71cf993a407154ad9d8dd027c88a374b0ed002a9 # v3.3
        with:
            coverageFile: coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run integration tests
        run: make integration-tests
