name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  contents: read
  pull-requests: write

jobs:
  ci-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run unit tests
        run: |
          uv run coverage run -m pytest app/tests/unit/
          uv run coverage report
          uv run coverage xml

      - name: Report Coverage
        uses: orgoro/coverage@v3.2
        with:
            coverageFile: coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run integration tests
        run: make integration-tests
